# Generated by Django 3.2.4 on 2021-06-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
                ('age', models.PositiveIntegerField(blank=True, default=0, verbose_name='Yoshi')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Millati')),
                ('bio', models.TextField(verbose_name='Biografiya')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Aktyor',
                'verbose_name_plural': 'Aktyorlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=30, verbose_name='Familya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=150, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Janr nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Post Category name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Maqola Kategoriya',
                'verbose_name_plural': 'Maqolalar Kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Post Tag name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Maqola Tegi',
                'verbose_name_plural': 'Maqolalar Teglari',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=450, verbose_name='Maqola nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('top', models.BooleanField(default=False, verbose_name='Top post')),
                ('body', models.TextField(verbose_name='Matni')),
                ('image', models.ImageField(upload_to='post_posters/', verbose_name='Poster')),
                ('author', models.CharField(max_length=50, verbose_name='Muallif')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='movie.postcategory')),
                ('tag', models.ManyToManyField(related_name='posts', to='movie.Tags')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Kino nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Poster')),
                ('director', models.CharField(max_length=100, verbose_name='Rejissor')),
                ('trailer_link', models.CharField(max_length=100, verbose_name='You tube link')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Davlati')),
                ('year', models.PositiveIntegerField(default=2021, verbose_name='Yili')),
                ('budget', models.PositiveIntegerField(default=0, verbose_name='Byudjet')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Reyting')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Korildi')),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actors', to='movie.actors')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='movie.genre')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism-Familya')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
            options={
                'verbose_name': 'Muhokama',
                'verbose_name_plural': 'Muhokamalar',
            },
        ),
    ]
