# Generated by Django 3.2.3 on 2021-06-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(default=1, upload_to='banner/', verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
