# Generated by Django 3.2.3 on 2021-06-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='xaqida',
            field=models.TextField(default=1, verbose_name='Kino xaqida'),
            preserve_default=False,
        ),
    ]
